# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/anastasiia/eyes/seg/segmenter/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sys
import os
import cv2
from PyQt5 import QtCore, QtWidgets
from PyQt5 import QtWidgets, uic
from PyQt5.QtWidgets import QApplication, QFileDialog, QMessageBox, QSlider, QVBoxLayout, QLabel
from PyQt5.QtWidgets import QLabel, QSizePolicy, QHBoxLayout, QPushButton
from PyQt5.QtGui import QImage, QPixmap
from PyQt5.QtCore import Qt
from mainwindow import Ui_MainWindow
os.environ["QT_QPA_PLATFORM"] = "xcb"



class ExampleApp(QtWidgets.QMainWindow, Ui_MainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)  # Настройка интерфейса


def main():
    app = QtWidgets.QApplication(sys.argv)  # Новый экземпляр QApplication
    window = ExampleApp()  # Создаем объект класса ExampleApp
    window.show()  # Показываем окно
    sys.exit(app.exec_())  # Запускаем приложение

if __name__ == '__main__':
    main()  # Запускаем функцию main()
